### ISSUE TITLE
[SPRINT 3] Wrong design

### ISSUE THREAD

**Issue by cuongtk8** [4pet-social/4pet.social#3]
<img width="1440" alt="Screen Shot 2020-11-07 at 2 13 46 PM" src="https://user-images.githubusercontent.com/34389409/98434567-8ed6ea80-2103-11eb-8f38-85bb85e83309.png">

**Comment by cuongtk8** [comment]
@tvc12

**Comment by 103cuong** [comment]
![Uploading Screen Shot 2020-12-04 at 9.25.20 PM.png…]()

**Comment by cuongtk8** [comment]
<img width="1440" alt="Screen Shot 2020-12-04 at 9 25 20 PM" src="https://user-images.githubusercontent.com/34389409/101175049-43b6e580-3677-11eb-8c40-51785d611cd2.png">

**Comment by cuongtk8** [comment]
@tvc12 still error
